### ISSUE TITLE
일일 예보 데이터가 표시되지 않습니다.

### ISSUE THREAD

**Issue by ntxlds** [dugurs/ha-weathernews#1]
어제까지는 잘 표시됐던 일일 예보가 나오지 않습니다.
시간별 예보는 제대로 표시되고 weather chart card에도 문제없이 나옵니다.
kr-weathernews쪽에 변경사항이 있는가요?

**Comment by dugurs** [comment]
저는 문제가 없는걸로 봐서 일시 문제 일것 같긴한데요.
오류가 있다면 오류 내용 확인 부탁 드립니다.

**Comment by ntxlds** [comment]
다시 일기예보 업데이트 되면서 정상적으로 돌아 왔네요.
일시적인 문제였나 봅니다.
