### ISSUE TITLE
Unmapped iconCode

### ISSUE THREAD

**Issue by ntxlds** [dugurs/ha-weathernews#2]
주로 야간에 날씨 업데이트 될 때 일일예보가 나타나지 않는 문제가 또 발생했습니다. 로그창에는 아래 내용으로 뜨고요.

WARNING (MainThread) [custom_components.weathernews.coordinator] Unmapped iconCode. (44 is Not Available (N/A)) "104.0".

const.py의 ATTR_CONDITION_PARTLYCLOUDY항목에 104를 추가해주니 일단 해결되긴 했습니다.

**Comment by dugurs** [comment]
104 아이콘 코드 추가 하로록 하겠습니다. 
주석에 104를 적어놓고 map지정을 빼먹었었나 봐요^^;
번개나 안개 같은 아직 지정되지 않은 (찾지 못한) 아이콘 코드가 남아있어 
지정되지 않은 아이콘이 날씨 상태가 있게 되면 다시 오류 날 수 있습니다. 다시 제보 부탁 드려요.
감사합니다.
