### ISSUE TITLE
Unmapped iconCode. (44 is Not Available (N/A)) "403.0"

### ISSUE THREAD

**Issue by ntxlds** [dugurs/ha-weathernews#3]
이번에는 403코드에러로 날씨 업데이트가 멈췄어요.
WARNING (MainThread) [custom_components.weathernews.coordinator] Unmapped iconCode. (44 is Not Available (N/A)) "403.0"

다음은 우리나라 기상청에서 사용하는 날씨 코드라고 하네요.

1. 100번대: 맑음/구름 상태
100: 맑음
101: 대체로 맑음
102: 구름 조금
103: 구름 많음
104: 흐림

2. 200번대: 흐림 및 안개 관련
200: 흐림
201: 약간 흐림
202: 구름 형성 중
210: 박무 (옅은 안개)
211: 연기
212: 먼지
213: 모래먼지
220: 안개
221: 산발적 안개

3. 300번대: 비, 눈, 진눈깨비
300: 비
301: 약한 비
302: 보통 비
303: 강한 비
304: 가랑비
311: 진눈깨비
312: 비와 진눈깨비
313: 비와 눈 섞임
314: 소나기
315: 비 또는 눈의 간헐적 발생

4. 400번대: 천둥·번개 관련 기상
400: 천둥·번개만
401: 천둥·번개와 약한 비
402: 천둥·번개와 강한 비
403: 천둥·번개와 눈 또는 진눈깨비
404: 천둥·번개와 우박
405: 천둥·번개와 폭설

5. 500번대: 눈, 폭설
500: 눈
501: 약한 눈
502: 보통 눈
503: 강한 눈
504: 폭설
511: 산발적 눈
512: 눈발 흩날림

6. 600번대: 기타 특이 현상
600: 황사
601: 황사 약함
602: 황사 보통
603: 황사 강함
604: 황사 매우 강함
610: 빙판길
611: 도로 결빙

7. 특수한 기상 코드
700번대 이상: 지역 또는 상황에 따라 추가 사용.
예: 710 (해일), 720 (태풍 영향권), 730 (폭염), 740 (한파).

**Comment by dugurs** [comment]
웨더뉴스 400은 눈인데, 우리나라 기상청 400천중번개로 일치하지 않는것 같고요.
웨더뉴스가 일본 기업이다보니 일본 기상청의 아이콘 코드를 사용하는것 같습니다.
코드 정리된것은 못찾아서 하나하나 대입해 보니 일치 하는것 같아, 없던 코드 찾아 추가 하였습니다.
https://www.kr-weathernews.com/mv4/html/assets/images/weather-icon-set/icon1/light/day/403.svg
https://www.jma.go.jp/bosai/forecast/img/403.svg
감사합니다.
